apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-erp-pod-to-database
  namespace: database
spec:
  podSelector:
    matchLabels:
      app: database-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: erp # Make sure the erp namespace is labeled with name=erp
      podSelector:
        matchLabels:
          app: erp-app
