apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: ecommerce
data:
  PORT: "8080"
  DB_PORT: "5432"
  DB_NAME: "ecommerce"
  DB_SCHEMA: "notification_svc"
  DB_SSLMODE: "disable"
