apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: ecommerce
  labels:
    app: shipping-service
spec:
  type: ClusterIP
  selector:
    app: shipping-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
