config:
  global:
    resolve_timeout: 5m

  route:
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 48h
    receiver: "discord"
    routes:
      - receiver: "null"
        matchers:
          - alertname =~ "Watchdog|InfoInhibitor"
      - receiver: "null"
        matchers:
          - alertname =~ "UnusedCpu|UnusedMemory"
      - receiver: "discord-noresolved"
        matchers:
          - alertname =~ "PodRestarted|OOMKilled"

  receivers:
    - name: "null"

    - name: "discord"
      webhook_configs:
        - url: "https://discord.com/api/webhooks/1374799011999121450/fiiOoSnLrGEE6K9qtTTcQQYb9VfFKF3i_yFv2JT-t6KHXjs7Ngf5Zu3SJc7a0MlTzHHr"
          send_resolved: true
          http_config:
            headers:
              Content-Type: application/json
          message: '{{ template "discord.message" . }}'

    - name: "discord-noresolved"
      webhook_configs:
        - url: "https://discord.com/api/webhooks/1374799011999121450/fiiOoSnLrGEE6K9qtTTcQQYb9VfFKF3i_yFv2JT-t6KHXjs7Ngf5Zu3SJc7a0MlTzHHr"
          send_resolved: false
          http_config:
            headers:
              Content-Type: application/json
          message: '{{ template "discord.message" . }}'

  templates:
    - '/etc/alertmanager/config/discord.tmpl'
