apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-storage-class
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  type: gp2
