apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: karpenter-c1
  region: us-east-2
  version: "1.31"

managedNodeGroups:
  - name: ng-b2
    instanceTypes: [c5.xlarge]
    minSize: 1
    maxSize: 4
    desiredCapacity: 1
    volumeSize: 20
    tags:
      Environment: Production
      karpenter.sh/discovery: karpenter-c1

# iam:
#   withOIDC: true
#   podIdentityAssociations:
#   - namespace: kube-system
#     serviceAccountName: karpenter
#     roleName: karpenter-c1-karpenter
#     permissionPolicyARNs:
#     - arn:aws:iam::605134426044:policy/KarpenterControllerPolicy-karpenter-c1

# iamIdentityMappings:
# - arn: "arn:aws:iam::605134426044:role/KarpenterNodeRole-karpenter-c1"
#   username: system:node:{{EC2PrivateDNSName}}
#   groups:
#   - system:bootstrappers
#   - system:nodes