apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: karpenter-c1  # Must match existing cluster
  region: us-east-2   # Must match cluster region

iam:
  podIdentityAssociations:
    - namespace: kube-system
      serviceAccountName: karpenter
      roleName: karpenter-c1-karpenter
      permissionPolicyARNs:
        - arn:aws:iam::605134426044:policy/KarpenterControllerPolicy-karpenter-c1