apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: your-cluster3  # Must match existing cluster
  region: us-east-1   # Must match cluster region

iam:
  podIdentityAssociations:
    - namespace: kube-system
      serviceAccountName: karpenter
      roleName: your-cluster3-karpenter
      permissionPolicyARNs:
        - arn:aws:iam::605134426044:policy/KarpenterControllerPolicy-your-cluster3