apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: meetup-may2025  # Must match existing cluster
  region: us-east-2   # Must match cluster region

iam:
  podIdentityAssociations:
    - namespace: kube-system
      serviceAccountName: karpenter
      roleName: meetup-may2025-karpenter
      permissionPolicyARNs:
        - arn:aws:iam::605134426044:policy/KarpenterControllerPolicy-meetup-may2025