apiVersion: apps/v1
kind: Deployment
metadata:
  name: stu-mnm-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stu-mnm-be  
  template:
    metadata:
      labels:
        app: stu-mnm-be
    spec:
      containers:
      - name: stu-mnm-be
        image: nasirnjs/stumnmbe:0.0.9
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz         
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: stu-mnm-be
spec:
  selector:
    app: stu-mnm-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
